name: Deploy Password Generator App

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to deploy'
        required: true

jobs:
  deploy:
    name: Deploy Go App to Server
    runs-on: ['self-hosted', 'Linux', 'X64', 'app-server']
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Stop Password Generator Service
      run: sudo systemctl stop password-generator.service

    - name: Download and Replace Files from AWS S3
      run: |
        sudo aws s3 cp s3://cloudhub-devops13/apps/${{ github.event.inputs.version }}/ /opt/passwd-gen/ --recursive

    - name: Start Password Generator Service
      run: sudo systemctl start password-generator.service

    - name: Verify Password Generator Service Status
      run: sudo systemctl status password-generator.service
