name: Deploy Password Generator App

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'build version'
        required: true

jobs:
  deploy_apps:
    name: Deploy Apps ${{ github.event.inputs.version }}
    runs-on: ['self-hosted', 'Linux', 'X64', 'app-server']
    
    steps:
    - name: Activate AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
        aws-region: ap-southeast-1

    - name: Download index.html to template directory
      run: |
        aws s3 cp s3://cloudhub-devops13/apps/${{ github.event.inputs.version }}/index.html /opt/passwd-gen/template/index.html

    - name: Download styles.css to static directory
      run: |
        aws s3 cp s3://cloudhub-devops13/apps/${{ github.event.inputs.version }}/styles.css /opt/passwd-gen/static/styles.css

    - name: Download password-generator binary
      run: |
        aws s3 cp s3://cloudhub-devops13/apps/${{ github.event.inputs.version }}/password-generator /opt/passwd-gen/password-generator
        sudo chmod +x /opt/passwd-gen/password-generator

    - name: Stop Password Generator Service
      run: sudo systemctl stop password-generator.service

    - name: Start Password Generator Service
      run: sudo systemctl start password-generator.service
